name: Master Pipeline.

on:
  push:
    branches:
      - main
      - 'feature/*'  # Trigger on any feature branch
    tags:
      - 'v*'  # Trigger on any version tag (e.g., v1.0, v2.0)

jobs:
  call-task-pipeline:
    uses: Hexa-UMB1/Called-Workflows-1/.github/workflows/maven.yml@main  # Reusable workflow call
    with:
      branch_or_tag: ${{ github.ref_name }}  # Pass the branch or tag name from the current push event
    secrets: inherit  # If you have secrets in the repository, inherit them

