name: Master Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'  # Trigger on any feature branch
    tags:
      - 'v*'  # Trigger on any version tag (e.g., v1.0, v2.0)

jobs:
  call-task-pipeline:
    runs-on: windows-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Determine if running on a tag or branch
        id: determine_branch_or_tag
        run: |
          echo "Ref: $GITHUB_REF"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=branch_or_tag::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=branch_or_tag::${GITHUB_REF#refs/heads/}"
          fi

      - name: Call Maven Task Pipeline (from another repository)
        uses: Hexa-UMB1/Called-Workflows-1/.github/workflows/maven.yml@main
        with:
          branch_or_tag: ${{ steps.determine_branch_or_tag.outputs.branch_or_tag }}
